### ISSUE TITLE
Getting error while connecting

### ISSUE THREAD

**Issue by singansh** [mstiri/p3270#1]
Tried on Python 3.6 with 

**conf file:**

hostname = 10.195.252.10
port = 992
model = 3279-2
traceFile = client.trace
LUName = LUPY0001
codePage = cp037
screensDir = C:\Users\asioh\PycharmProjects\Testproj\
*********************************************************************
**Code:**
from p3270 import P3270Client

my_client = P3270Client(configFile='config.cfg')
if not my_client.connect():
    print('Connection failed !')
    exit(1)
print("connected")

**********************************************************************
**Error**
  File "C:/Users/asioh/PycharmProjects/Testproj/rest.py", line 10, in <module>
    my_client = P3270Client(configFile='config.cfg')
  File "C:\Users\asioh\AppData\Local\Python\Python36-32\lib\site-packages\p3270\p3270.py", line 97, in __init__
    self.s3270 = S3270(self.args)
  File "C:\Users\asioh\AppData\Local\Python\Python36-32\lib\site-packages\p3270\p3270.py", line 27, in __init__
    stderr=subprocess.PIPE)
  File "C:\Users\asioh\AppData\Local\Python\Python36-32\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Users\asioh\AppData\Local\Python\Python36-32\lib\subprocess.py", line 992, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
********************************************************************************

Can you please help

**Comment by mstiri** [comment]
Hi @singansh, 
From the errors, I see that you are trying to run your script on a Windows machine. 
Unfortunately, as it is said in the documentation, the library is only supported in Linux Operating Systems. 
Try to use a Linux machine (or VM). If you have any problem I'll be glad to help :)

**Comment by KalraAkshay** [comment]
@mstiri, Could you please help me out here? I know, this library only works for Linux, but how we can use this in windows?

**Comment by mstiri** [comment]
@KalraAkshay, you can set up a Linux Virtual Machine (using VirtualBox for example) in your environment, you can be able to use the library.
