### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by camposleyba** [mstiri/p3270#10]
Hi, trying to start 'my_client = P3270Client(configFile='p3270.cfg')' with a .cfg file I created and placed in the directory. When running is stating the following error:

FileNotFoundError: [WinError 2] The system cannot find the file specified

this is the config file: 

# Target hostname 
hostname = 'myhost'
# Port
port = 992
# Model Name: Default 3279-2
model = 3279-2
# TraceFile
traceFile = client.trace
# LU name to use
#LUName = LUPY0001
# EBCDIC character set to use for the host
codePage = cp037
# The file where all the screens should be saved
#screensDir =

**Comment by manuelcribeiro** [comment]
I had this issue just use full path to file

**Comment by camposleyba** [comment]
I used full path, but I ya e a windows machine, so on another thread that it does not work on windows, that has not been changed right?

Enviado desde mi iPhone

**Comment by mstiri** [comment]
Hello, 
It seems that you are using Windows as an OS. Unfortunately, Windows OS is not supported.
