### ISSUE TITLE
Servname not supported for ai_socktype

### ISSUE THREAD

**Issue by neilc2019** [mstiri/p3270#2]
hi,
I'm trying to use this library tool on Linux el7 but getting "Servname not supported for ai_socktype" error when trying to connect.   Below is the trace and cfg file. Am I missing something?

$ python3.6 test.py
Connection failed !

 Version: s3270 v3.3.12ga12 Mon Jan 27 16:40:31 EST 2014 mockbuild
 Build options: --enable-ansi --enable-apl --enable-dbcs --enable-ft --enable-local-process --enable-tn3270e --enable-trace --with-ssl
 Command: s3270 s3270 -model 3279-2 -port 23 -trace -tracefile client.trace
 Model 3279-2-E, 24 rows x 80 cols, extended data stream, color emulation, bracket charset
 Locale codeset: UTF-8
 Host codepage: 37
 Data stream:
20190812.154242.449 Enabling input for PeerScript[1]
20190812.154242.449 Waiting for events
20190812.154242.449 Got 1 event
20190812.154242.449 Input for PeerScript[1] IDLE reading fd 0
20190812.154242.449 Input for PeerScript[1] IDLE complete nr=24
20190812.154242.449 PeerScript[1] running
20190812.154242.449 PeerScript[1]: 'Connect(B:166.37.160.2)'
20190812.154242.449  Script -> Connect("B:166.37.160.2")
20190812.154242.460 B/166.37.160.2: Servname not supported for ai_socktype
20190812.154242.461 Keyboard unlock(kybd_connect) -NOT_CONNECTED
20190812.154242.461 Keyboard lock(kybd_connect) +NOT_CONNECTED
20190812.154242.461 Waiting for events
20190812.154242.469 Got 1 event
20190812.154242.469 Input for PeerScript[1] IDLE reading fd 0
20190812.154242.470 Input for PeerScript[1] IDLE complete nr=0
20190812.154242.470 EOF PeerScript[1]
20190812.154242.470 PeerScript[1] complete
20190812.154242.470 Trace stopped

# Target hostname
hostname = 166.37.160.2
# Port
port = 23
# Model Name: Default 3279-2
model = 3279-2
# TraceFile
traceFile = client.trace
# LU name to use
#LUName = CIADCSC5
# EBCDIC character set to use for the host
#codePage = cp037
# The file where all the screens should be saved
screensDir = /vzwhome/chikone/p3270/

**Comment by mstiri** [comment]
Hi, 
I've never faced a similar problem. 
Is it a RedHat 7 ? 
The target host allow connections to port 23 from this host ? 
Cay you test that there is no network issue to connect to port 23 ?
Example with netcat, from your test host :
**$ nc -zv  166.37.160.2 23**

**Comment by neilc2019** [comment]
It might be a Redhat 7 issue.  I just hardcoded the IP in the p3270.py and changed connect to L: and it worked.  Thanks

 def __init__(self, luName=None, hostName='166.xxx.xxx.xxx', hostPort='23', modelName='3279-2', configFile=None):

return self.s3270.do('Connect(L:{})'.format(self.conf.hostName))
