### ISSUE TITLE
Unable to Stablish a SSL connection

### ISSUE THREAD

**Issue by abdelmaster** [mstiri/p3270#3]
**Problem Determination**

1. I'm able to access the system using x3270
`x3270 -noverifycert L:X.X.X.X:XX`
2. I try by modifying the p3270.py:
```
    def connect(self):
        """ Connect to the host
        """
        if self.conf.luName:
            logger.info("Connect to host [{}] with LUName: [{}]".format(self.conf.hostName, self.conf.luName))
            **return self.s3270.do('Connect(L:{}@{})'.format(self.conf.luName,self.conf.hostName))**
        else:
            logger.info("Connect to host [{}] with no LUName".format(self.conf.hostName))
            return self.s3270.do('Connect(L:{})'.format(self.conf.hostName))
```

And I got the following error which was expected (I face this issue while trying to connect using x3270):
```
20200109.195907.698 SSL: SSLHandshake: invalid certificate chain
20200109.195907.698 Output for Macro[2]: 'data: SSL: SSLHandshake: invalid certificate chain'
```

3.- I tried to connect using s3270 on the command line:

**From the command Line I'm able to establish connection**
```

s3270 -noverifycert L:X.X.X.X:XX 


U F U C(X.X.X.X) I 4 43 80 38 15 0x0 -
ok
U F U C(X.X.X.X) I 4 43 80 38 15 0x0 -
ok
```

From here I tried to add the following "-noverifycert" to this part of the code:

```
def connect(self):
        """ Connect to the host
        """
        if self.conf.luName:
            logger.info("Connect to host [{}] with LUName: [{}]".format(self.conf.hostName, self.conf.luName))
            **return self.s3270.do('Connect({},L:{}@{})'.format(self.conf.cert,self.conf.luName,self.conf.hostName))**
        else:
            logger.info("Connect to host [{}] with no LUName".format(self.conf.hostName))
            return self.s3270.do('Connect(L:{})'.format(self.conf.hostName))
```

And I'm getting the following error:

```
20200109.194957.267 PeerScript[1]: 'Connect(-noverifycert,L:B:00000001@X.X.X.X)'
20200109.194957.267 Disabling input for PeerScript[1]
20200109.194957.267 Macro[2] running
20200109.194957.267 Macro[2]: 'Connect(-noverifycert,L:B:00000001@X.X.X.X)'
20200109.194957.267 Script -> Connect("-noverifycert", "L:B:00000001@X.X.X.X")
20200109.194957.267 Connect requires 1 argument
20200109.194957.267 Output for Macro[2]: 'data: Connect requires 1 argument'
20200109.194957.267 Macro[2] error
20200109.194957.267 Macro[2] complete
20200109.194957.267 PeerScript[1] continuing
20200109.194957.267 Output for PeerScript[1]: 'L U U N N 2 24 80 0 0 0x0 -'
20200109.194957.267 Output for PeerScript[1]: 'error'
20200109.194957.267 Enabling input for PeerScript[1]
20200109.194957.267 Waiting for events
20200109.194957.267 Got 0 events
20200109.194957.268 Waiting for events
20200109.194957.280 Got 1 event
20200109.194957.280 Input for PeerScript[1] IDLE reading fd 0
20200109.194957.280 Input for PeerScript[1] IDLE complete, nr=0
```

Do you have any idea or hint of how to include the option -noverifycert into the command?

**Comment by mstiri** [comment]
@abdelmaster thank you for reporting the problem. 
I'm looking into this. A new release with the option to disable Certificate verification is coming.

**Comment by abdelmaster** [comment]
Thanks @mstiri if any how I can help just let me know

**Comment by mstiri** [comment]
@abdelmaster 
I've committed a branch with the new feature.
Just follow these two steps to use it: 
1. Checkout the branch (git checkout feature/option_disable_ssl)
2. Add the option (verifyCert = no) to the configuration file. (see the configuration file provided as example: [p3270.cfg](https://github.com/mstiri/p3270/blob/feature/option_disable_ssl/p3270/p3270.cfg))

Let me know if this helped solving your issue.

**Comment by abdelmaster** [comment]
Thanks for the fast response.
I test the changes and I modified this line in order to establish the connection:

`    def connect(self):
        """ Connect to the host
        """
        if self.conf.luName:
            logger.info("Connect to host [{}] with LUName: [{}]".format(self.conf.hostName, self.conf.luName))
            return self.s3270.do('Connect(**L**:{}@{})'.format(self.conf.luName,self.conf.hostName))
        else:
            logger.info("Connect to host [{}] with no LUName".format(self.conf.hostName))
            return self.s3270.do('Connect(**L**:{})'.format(self.conf.hostName))
`
from documentation s3270:

Prepending an L: onto hostname causes s3270 to first create an SSL tunnel to the host, and then create a TN3270 session inside the tunnel. (This function is supported only if s3270 was built with SSL/TLS support). Note that TLS-encrypted sessions using the TELNET START-TLS option are negotiated with the host automatically; for these sessions the L: prefix should not be used. 

[s3270 manual](http://x3270.bgp.nu/Unix/s3270-man.html)

I think we need to enable this option if the verifyCert is going to be used since we need to establish the ssl tunnel.

**Comment by mstiri** [comment]
@abdelmaster 
I've added another option (to set in the configuration file) in the same branch "feature/option_disable_ssl".
You will need to add the parameter (enableTLS = yes) to the configuration file. 
In your case, you will need to disable certificate verification (verifyCert = no). 
Let me know if this suits your need, or if there is any other problems.

**Comment by abdelmaster** [comment]
I test the last changes and now is working perfectly!!
